# Generated by Django 5.0 on 2024-11-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0016_agentvodabundleprice_superagentvodabundleprice_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='topuprequest',
        #     name='payment_channel',
        # ),
        migrations.AddField(
            model_name='admininfo',
            name='ishare_source',
            field=models.CharField(blank=True, choices=[('Gyasi', 'Gyasi'), ('Value4Moni', 'Value4Moni')], default='Value4Moni', max_length=250, null=True),
        ),
    ]
