# Generated by Django 5.0 on 2024-11-09 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0017_admininfo_paystack_active_afaregistration_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransactionn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=250)),
                ('transaction_amount', models.FloatField()),
                ('transaction_use', models.CharField(max_length=250)),
                ('new_balance', models.FloatField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
