# Generated by Django 5.0 on 2024-11-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0017_admininfo_ishare_source_admininfo_paystack_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afaregistration',
            name='transaction_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Processing', 'Processing'), ('Failed', 'Failed')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='bigtimetransaction',
            name='transaction_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Processing', 'Processing'), ('Failed', 'Failed')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='mtntransaction',
            name='transaction_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Completed', max_length=100),
        ),
    ]
