# Generated by Django 5.0 on 2024-11-09 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0017_admininfo_paystack_active_afaregistration_amount_and_more'),
    ]

    operations = [

    ]
