# Generated by Django 5.0 on 2024-11-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0018_topuprequestt_wallettransactionn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topuprequest',
            name='payment_channel',
        ),
    ]
